### ISSUE TITLE
knex missing dependency and still fails after install

### ISSUE THREAD

**Issue by grantcarthew** [stevepapa/veria#7]
Hi,
Thought I would give `veria` a spin on my Debian system.
`npm start` failed with a missing package `knex`.
I installed `knex` and this error occured:

```sh
➜  veria git:(master) ✗ npm start

> veria@0.2.2 start /home/grant/veria
> node ./index

/home/grant/veria/node_modules/bookshelf/bookshelf.js:37
  if (!knex.client || !(knex.client instanceof Knex.ClientBase)) {
                                                   ^

TypeError: Expecting a function in instanceof check, but got undefined
    at new Bookshelf (/home/grant/veria/node_modules/bookshelf/bookshelf.js:37:52)
    at Function.Bookshelf.initialize (/home/grant/veria/node_modules/bookshelf/bookshelf.js:120:10)
    at Object.<anonymous> (/home/grant/veria/models/database.js:4:30)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/grant/veria/models/post.js:1:84)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/home/grant/.npm-packages/bin/npm" "start"
npm ERR! node v5.3.0
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE
npm ERR! veria@0.2.2 start: `node ./index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the veria@0.2.2 start script 'node ./index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the veria package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs veria
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls veria
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/grant/veria/npm-debug.log
➜  veria git:(master) ✗
```

Just letting you know. I am not going to fault find this any further.

**Comment by stevepapa** [comment]
Thank you, this issue was resolved as part of #3
